# Generated by Django 4.1.5 on 2023-01-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Home Slide title')),
                ('name', models.CharField(max_length=30, verbose_name='Home Slide name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Home Slide Img')),
            ],
            options={
                'verbose_name': 'HomeSlider',
                'verbose_name_plural': 'HomeSliders',
            },
        ),
    ]
