# Generated by Django 4.1.5 on 2023-01-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Product Name')),
                ('short_description', models.CharField(max_length=120, verbose_name='Product Short Description')),
                ('description', models.TextField(verbose_name='Product Description')),
                ('price', models.IntegerField(verbose_name='Product Description')),
                ('img', models.ImageField(upload_to='media', verbose_name='Product Image')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
