# Generated by Django 4.1.5 on 2023-02-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='Main title')),
                ('second_title', models.CharField(max_length=45, verbose_name='second title')),
                ('text', models.TextField(verbose_name='short about')),
                ('img', models.ImageField(upload_to='media', verbose_name='Product Image')),
            ],
        ),
    ]
