# Generated by Django 4.1.5 on 2023-02-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_calltoaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltoaction',
            name='text',
            field=models.CharField(max_length=120, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='title',
            field=models.CharField(max_length=35, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='shortabout',
            name='second_title',
            field=models.CharField(max_length=45, verbose_name='Second title'),
        ),
        migrations.AlterField(
            model_name='shortabout',
            name='text',
            field=models.TextField(verbose_name='Short about'),
        ),
    ]
