# Generated by Django 4.1.5 on 2023-02-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_calltoaction_text_alter_calltoaction_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltoaction',
            name='button',
            field=models.CharField(default=222, max_length=25, verbose_name='Button text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortabout',
            name='button',
            field=models.CharField(default=222, max_length=25, verbose_name='Button text'),
            preserve_default=False,
        ),
    ]
