# Generated by Django 4.1.5 on 2023-02-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_calltoaction_button_remove_shortabout_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortabout',
            name='button',
            field=models.CharField(default=1, max_length=25, verbose_name='Button text'),
            preserve_default=False,
        ),
    ]
