# Generated by Django 4.1.5 on 2023-02-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_aboutpagehead'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstTitle', models.CharField(max_length=30, verbose_name='Main Title')),
                ('secondTitle', models.CharField(max_length=30, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('img', models.ImageField(upload_to='media', verbose_name='AboutUs Img')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
